#!/bin/bash
# Nightly Build - Automated summary and consolidation
# Runs at 11 PM Sydney time daily

TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
DATE=$(date '+%Y-%m-%d')
REPORT=""

cd /home/skux/.openclaw/workspace

# Header
REPORT="🌙 **Nightly Build - ${TIMESTAMP}** 🦞

───"

# Section 1: Crypto Alpha Summary
REPORT+="
🎯 **Crypto Alpha Digest**
"

if [ -f "alpha_results_v53.json" ]; then
    GRADE_A_COUNT=$(python3 -c "import json; data=json.load(open('alpha_results_v53.json')); print(len(data))" 2>/dev/null || echo "0")
    if [ "$GRADE_A_COUNT" -gt 0 ]; then
        REPORT+="• Grade A tokens found today: **$GRADE_A_COUNT** ✅
"
        # Get details of each token
        python3 << EOF 2>/dev/null >> /tmp/crypto_temp.txt
import json
with open('alpha_results_v53.json') as f:
    data = json.load(f)
    for token in data[:3]:
        age = token.get('age_hours', 0)
        ca = token.get('ca', 'unknown')[:20] + '...'
        holders = token.get('holders', 0)
        print(f"  \u2022 {ca} | Age: {age:.1f}h | Holders: {holders}")
EOF
        if [ -f "/tmp/crypto_temp.txt" ]; then
            REPORT+=$(cat /tmp/crypto_temp.txt)
            REPORT+="
"
            rm /tmp/crypto_temp.txt
        fi
    else
        REPORT+="• No Grade A tokens found today
"
    fi
else
    REPORT+="• No scan results yet
"
fi

# Section 2: Memory Summary
REPORT+="
📝 **Memory Consolidation**
"

if [ -f "memory/${DATE}.md" ]; then
    LINES=$(wc -l < "memory/${DATE}.md")
    REPORT+="• Daily memory: **$LINES lines** captured
"
else
    REPORT+="• No daily memory yet today
"
fi

SKILL_COUNT=$(ls -1 skills/*/SKILL.md 2>/dev/null | wc -l)
REPORT+="• Active skills: **$SKILL_COUNT**
"

# Section 3: System Status
REPORT+="
⚙️ **System Status**
"

CRON_COUNT=$(crontab -l 2>/dev/null | grep -c "openclaw" || echo "0")
REPORT+="• Cron jobs: **$CRON_COUNT active**
"

cd /home/skux/.openclaw/workspace
git status --short > /tmp/git_status.txt 2>/dev/null
GIT_CHANGES=$(wc -l < /tmp/git_status.txt)
if [ "$GIT_CHANGES" -gt 0 ]; then
    REPORT+="• Uncommitted changes: **$GIT_CHANGES files**
"
else
    REPORT+="• Repo: clean ✅
"
fi

# Section 4: Moltbook Activity
REPORT+="
🦞 **Moltbook Activity**
"

if [ -f "memory/moltbook_state.json" ]; then
    LAST_POST=$(python3 -c "import json; data=json.load(open('memory/moltbook_state.json')); print(data.get('lastPost', 'unknown')[:10])" 2>/dev/null)
    POSTS=$(python3 -c "import json; data=json.load(open('memory/moltbook_state.json')); print(data.get('posts', 0))" 2>/dev/null)
    KARMA=$(python3 -c "import json; data=json.load(open('memory/moltbook_state.json')); print(data.get('karma', 0))" 2>/dev/null)
    REPORT+="• Total posts: **$POSTS** | Karma: **$KARMA**
"
    REPORT+="• Last post: $LAST_POST
"
else
    REPORT+="• No Moltbook state found
"
fi

# Section 5: Tomorrow's Draft
REPORT+="
📅 **Tomorrow's Draft**
"

# Check if we already have a tomorrow.md
TOMORROW=$(date -d "+1 day" '+%Y-%m-%d' 2>/dev/null || date -v+1d '+%Y-%m-%d' 2>/dev/null)
if [ ! -f "memory/${TOMORROW}.md" ]; then
    cat > "memory/${TOMORROW}.md" << EOF
# ${TOMORROW} - Tomorrow's Tasks

## Incoming from Nightly Build
- [ ] Review crypto tokens that hit 6h/12h/24h marks
- [ ] Check Moltbook for replies/mentions
- [ ] Scan for new skills on ClawdHub
- [ ] Update MEMORY.md with today's learnings

## Notes
*Generated by Nightly Build at ${TIMESTAMP}*
EOF
    REPORT+="• Created memory/${TOMORROW}.md ✅
"
else
    REPORT+="• Tomorrow's draft already exists ✅
"
fi

# Footer
REPORT+="
───
*Auto-generated | Tip: Check memory/${TOMORROW}.md for tomorrow's tasks*
"

# Send to Telegram
python3 << EOF
import requests
import json

TOKEN = "8244363046:AAELXewfUaBAUfZpSkCXAv3KEgrp3SVVkNU"
CHAT_ID = "6610224534"

message = """${REPORT}"""

url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": message,
    "parse_mode": "Markdown",
    "disable_web_page_preview": True
}

try:
    r = requests.post(url, json=payload, timeout=30)
    if r.status_code == 200:
        print("✅ Nightly Build sent to Telegram")
    else:
        print(f"❌ Failed: {r.status_code}")
except Exception as e:
    print(f"❌ Error: {e}")
EOF

echo "Nightly Build complete: ${TIMESTAMP}"
