#!/usr/bin/env python3
"""
Proactive Engine - Monitors user patterns 24/7 and initiates actions.

Monitors:
- Missed morning routine? → "Sick day mode activated"
- Inbox growing? → "Want me to summarize urgent emails?"
- Calendar conflict? → "Detected overlap, here's resolution"
- Usually check crypto at 8am? → "Here's overnight summary at 7:55am"
"""

import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Any, Callable
from dataclasses import dataclass, asdict
from enum import Enum


class AnomalyType(Enum):
    """Types of anomalies that can be detected."""
    ROUTINE_MISSED = "routine_missed"
    INBOX_BACKLOG = "inbox_backlog"
    CALENDAR_CONFLICT = "calendar_conflict"
    UNUSUAL_INACTIVITY = "unusual_inactivity"
    BUDGET_OVERRUN = "budget_overrun"
    DEADLINE_APPROACHING = "deadline_approaching"


class OpportunityType(Enum):
    """Types of opportunities that can be detected."""
    MARKET_MOVEMENT = "market_movement"
    JOB_MATCH = "job_match"
    LEARNING_MOMENT = "learning_moment"
    OPTIMIZATION_CANDIDATE = "optimization_candidate"
    SOCIAL_ENGAGEMENT = "social_engagement"


@dataclass
class UserPattern:
    """Represents a learned user pattern."""
    pattern_id: str
    pattern_type: str  # 'time', 'action', 'sequence', 'threshold'
    trigger_condition: Dict[str, Any]
    typical_response: Optional[str]
    frequency: int  # How often this pattern occurs
    last_observed: datetime
    confidence: float  # 0.0 to 1.0


@dataclass
class ProactiveSuggestion:
    """A suggestion generated by the proactive engine."""
    suggestion_id: str
    suggestion_type: str  # 'anomaly' or 'opportunity'
    title: str
    description: str
    priority: int  # 1 (highest) to 5 (lowest)
    action_items: List[str]
    auto_execute: bool  # Whether this can auto-execute
    requires_approval: bool
    context: Dict[str, Any]
    confidence: float


class ProactiveEngine:
    """
    Monitors user patterns 24/7 and proactively suggests or executes actions.
    """
    
    def __init__(self, omnibot=None, patterns_file: Optional[str] = None):
        self.logger = logging.getLogger("Omnibot.ProactiveEngine")
        self.omnibot = omnibot
        
        # Pattern storage
        self.patterns_file = Path(patterns_file) if patterns_file else Path(__file__).parent / "user_patterns.json"
        self.user_patterns: List[UserPattern] = []
        self.pattern_callbacks: Dict[str, List[Callable]] = {}
        
        # Activity tracking
        self.last_activity = self._get_last_activity()
        self.activity_history: List[Dict] = []
        
        # Anomaly thresholds
        self.anomaly_thresholds = {
            "routine_variance_minutes": 30,
            "inbox_max_unread": 50,
            "calendar_conflict_minutes": 15,
            "inactivity_hours": 4,
            "budget_variance_percent": 20,
            "deadline_warning_hours": 24
        }
        
        # Load existing patterns
        self._load_patterns()
        
        self.logger.info("ProactiveEngine initialized")
    
    def _get_last_activity(self) -> datetime:
        """Get timestamp of last recorded activity."""
        if self.patterns_file.exists():
            try:
                data = json.loads(self.patterns_file.read_text())
                return datetime.fromisoformat(data.get("last_activity", datetime.now().isoformat()))
            except Exception:
                pass
        return datetime.now()
    
    def _load_patterns(self):
        """Load learned user patterns from storage."""
        if not self.patterns_file.exists():
            self.logger.info("No existing patterns found, starting fresh")
            return
        
        try:
            data = json.loads(self.patterns_file.read_text())
            self.user_patterns = [
                UserPattern(**p) for p in data.get("patterns", [])
            ]
            self.logger.info(f"Loaded {len(self.user_patterns)} user patterns")
        except Exception as e:
            self.logger.error(f"Failed to load patterns: {e}")
    
    def _save_patterns(self):
        """Save learned patterns to storage."""
        try:
            data = {
                "last_updated": datetime.now().isoformat(),
                "last_activity": datetime.now().isoformat(),
                "patterns": [asdict(p) for p in self.user_patterns]
            }
            self.patterns_file.write_text(json.dumps(data, indent=2, default=str))
        except Exception as e:
            self.logger.error(f"Failed to save patterns: {e}")
    
    # ==================== PATTERN LEARNING ====================
    
    def record_activity(self, activity_type: str, metadata: Optional[Dict] = None):
        """
        Record a user activity for pattern learning.
        
        Args:
            activity_type: Type of activity (e.g., 'check_email', 'start_work')
            metadata: Additional activity context
        """
        activity = {
            "timestamp": datetime.now().isoformat(),
            "type": activity_type,
            "metadata": metadata or {}
        }
        self.activity_history.append(activity)
        self.last_activity = datetime.now()
        
        # Update patterns based on new activity
        self._update_patterns(activity)
        
        # Limit history size
        if len(self.activity_history) > 1000:
            self.activity_history = self.activity_history[-500:]
        
        self.logger.debug(f"Recorded activity: {activity_type}")
    
    def _update_patterns(self, activity: Dict):
        """Update learned patterns based on new activity."""
        activity_time = datetime.fromisoformat(activity["timestamp"])
        activity_type = activity["type"]
        
        # Check for time-based patterns
        existing_pattern = None
        for pattern in self.user_patterns:
            if pattern.pattern_type == "time" and pattern.trigger_condition.get("activity_type") == activity_type:
                existing_pattern = pattern
                break
        
        if existing_pattern:
            # Update existing pattern
            old_time = existing_pattern.trigger_condition.get("typical_hour", 0)
            new_time = activity_time.hour + activity_time.minute / 60
            # Moving average
            existing_pattern.trigger_condition["typical_hour"] = (old_time * existing_pattern.frequency + new_time) / (existing_pattern.frequency + 1)
            existing_pattern.frequency += 1
            existing_pattern.last_observed = activity_time
            existing_pattern.confidence = min(1.0, existing_pattern.confidence + 0.01)
        else:
            # Create new pattern
            new_pattern = UserPattern(
                pattern_id=f"time_{activity_type}_{datetime.now().timestamp()}",
                pattern_type="time",
                trigger_condition={
                    "activity_type": activity_type,
                    "typical_hour": activity_time.hour + activity_time.minute / 60
                },
                typical_response=None,
                frequency=1,
                last_observed=activity_time,
                confidence=0.5
            )
            self.user_patterns.append(new_pattern)
        
        self._save_patterns()
    
    def learn_pattern(self, pattern_type: str, condition: Dict, 
                     response: Optional[str] = None) -> str:
        """
        Manually teach the engine a new pattern.
        
        Args:
            pattern_type: Type of pattern ('time', 'action', 'sequence', 'threshold')
            condition: Pattern trigger condition
            response: Optional expected response
            
        Returns:
            Pattern ID
        """
        pattern = UserPattern(
            pattern_id=f"manual_{pattern_type}_{datetime.now().timestamp()}",
            pattern_type=pattern_type,
            trigger_condition=condition,
            typical_response=response,
            frequency=0,
            last_observed=datetime.now(),
            confidence=0.8
        )
        self.user_patterns.append(pattern)
        self._save_patterns()
        
        self.logger.info(f"Learned new pattern: {pattern.pattern_id}")
        return pattern.pattern_id
    
    # ==================== ANOMALY DETECTION ====================
    
    def detect_anomaly(self) -> Optional[Dict]:
        """
        Detect anomalies in user behavior.
        
        Returns:
            Anomaly information if detected, None otherwise
        """
        anomalies = []
        
        # Check for missed routine
        routine_anomaly = self._check_missed_routine()
        if routine_anomaly:
            anomalies.append(routine_anomaly)
        
        # Check for unusual inactivity
        inactivity_anomaly = self._check_inactivity()
        if inactivity_anomaly:
            anomalies.append(inactivity_anomaly)
        
        # Check external data sources if omnibot available
        if self.omnibot:
            inbox_anomaly = self._check_inbox_backlog()
            if inbox_anomaly:
                anomalies.append(inbox_anomaly)
            
            calendar_anomaly = self._check_calendar_conflicts()
            if calendar_anomaly:
                anomalies.append(calendar_anomaly)
        
        if anomalies:
            return max(anomalies, key=lambda x: x.get("severity", 0))
        return None
    
    def _check_missed_routine(self) -> Optional[Dict]:
        """Check if user missed their typical routine."""
        now = datetime.now()
        
        # Look for morning routine patterns
        morning_patterns = [
            p for p in self.user_patterns
            if p.pattern_type == "time" and 
            5 <= p.trigger_condition.get("typical_hour", 12) <= 10 and
            p.confidence > 0.7
        ]
        
        for pattern in morning_patterns:
            typical_hour = pattern.trigger_condition.get("typical_hour", 8)
            typical_time = now.replace(hour=int(typical_hour), 
                                       minute=int((typical_hour % 1) * 60))
            
            # Check if we're past the typical time
            if now > typical_time + timedelta(minutes=self.anomaly_thresholds["routine_variance_minutes"]):
                # Check if activity already happened today
                today_activity = [
                    a for a in self.activity_history
                    if a["type"] == pattern.trigger_condition.get("activity_type") and
                    datetime.fromisoformat(a["timestamp"]).date() == now.date()
                ]
                
                if not today_activity:
                    return {
                        "type": AnomalyType.ROUTINE_MISSED,
                        "severity": 3,
                        "description": f"Missed typical {pattern.trigger_condition.get('activity_type')} routine",
                        "typical_time": typical_time.isoformat(),
                        "pattern": pattern
                    }
        return None
    
    def _check_inactivity(self) -> Optional[Dict]:
        """Check for unusual inactivity."""
        inactive_duration = datetime.now() - self.last_activity
        
        if inactive_duration > timedelta(hours=self.anomaly_thresholds["inactivity_hours"]):
            return {
                "type": AnomalyType.UNUSUAL_INACTIVITY,
                "severity": 2,
                "description": f"No activity for {inactive_duration.total_seconds() / 3600:.1f} hours",
                "inactive_hours": inactive_duration.total_seconds() / 3600
            }
        return None
    
    def _check_inbox_backlog(self) -> Optional[Dict]:
        """Check for growing inbox backlog."""
        # This would integrate with email client
        # Simulated for now
        return None
    
    def _check_calendar_conflicts(self) -> Optional[Dict]:
        """Check for calendar conflicts."""
        # This would integrate with calendar API
        # Simulated for now
        return None
    
    # ==================== OPPORTUNITY DETECTION ====================
    
    def detect_opportunity(self) -> Optional[Dict]:
        """
        Detect opportunities for proactive value-add.
        
        Returns:
            Opportunity information if detected, None otherwise
        """
        opportunities = []
        
        # Check for learning moments
        learning = self._check_learning_opportunity()
        if learning:
            opportunities.append(learning)
        
        # Check for optimization candidates
        optimization = self._check_optimization_opportunity()
        if optimization:
            opportunities.append(optimization)
        
        # Check for timely suggestions
        timely = self._check_timely_suggestion()
        if timely:
            opportunities.append(timely)
        
        if opportunities:
            return max(opportunities, key=lambda x: x.get("value_score", 0))
        return None
    
    def _check_learning_opportunity(self) -> Optional[Dict]:
        """Detect opportunities for learning/help."""
        # Analyze recent activity for patterns where help might be useful
        recent_patterns = self._analyze_recent_patterns()
        
        if recent_patterns.get("repetitive_task_count", 0) > 5:
            return {
                "type": OpportunityType.LEARNING_MOMENT,
                "value_score": 7,
                "description": f"Detected repetitive task '{recent_patterns['task_name']}' - automation candidate",
                "suggested_action": "Learn to automate this task"
            }
        return None
    
    def _check_optimization_opportunity(self) -> Optional[Dict]:
        """Detect optimization opportunities."""
        # Look for suboptimal patterns
        return None
    
    def _check_timely_suggestion(self) -> Optional[Dict]:
        """Check for time-sensitive suggestions."""
        now = datetime.now()
        
        # Check if user typically checks specific data at this time
        for pattern in self.user_patterns:
            if pattern.pattern_type == "time" and pattern.confidence > 0.8:
                typical_hour = pattern.trigger_condition.get("typical_hour", 0)
                if abs(now.hour + now.minute / 60 - typical_hour) < 0.25:  # Within 15 min
                    return {
                        "type": OpportunityType.MARKET_MOVEMENT,
                        "value_score": 6,
                        "description": f"User typically checks {pattern.trigger_condition.get('activity_type')} around this time",
                        "suggested_action": f"Prepare {pattern.trigger_condition.get('activity_type')} summary",
                        "pattern": pattern
                    }
        return None
    
    def _analyze_recent_patterns(self) -> Dict:
        """Analyze recent activity patterns."""
        # Group recent activities
        recent = self.activity_history[-50:]
        task_counts = {}
        
        for activity in recent:
            task_type = activity["type"]
            task_counts[task_type] = task_counts.get(task_type, 0) + 1
        
        if task_counts:
            most_common = max(task_counts.items(), key=lambda x: x[1])
            return {
                "repetitive_task_count": most_common[1],
                "task_name": most_common[0]
            }
        return {"repetitive_task_count": 0}
    
    # ==================== MAIN CHECK FUNCTION ====================
    
    def check_and_intervene(self) -> Optional[ProactiveSuggestion]:
        """
        Main entry point - called by scheduler every 15 minutes.
        
        Returns:
            ProactiveSuggestion if action needed, None otherwise
        """
        self.logger.debug("Running proactive check...")
        
        # Check for anomalies first (higher priority)
        anomaly = self.detect_anomaly()
        if anomaly:
            suggestion = self._create_anomaly_suggestion(anomaly)
            self.logger.info(f"Detected anomaly: {suggestion.title}")
            return suggestion
        
        # Check for opportunities
        opportunity = self.detect_opportunity()
        if opportunity:
            suggestion = self._create_opportunity_suggestion(opportunity)
            self.logger.info(f"Detected opportunity: {suggestion.title}")
            return suggestion
        
        return None
    
    def _create_anomaly_suggestion(self, anomaly: Dict) -> ProactiveSuggestion:
        """Create a suggestion from an anomaly."""
        anomaly_type = anomaly.get("type")
        
        if anomaly_type == AnomalyType.ROUTINE_MISSED:
            return ProactiveSuggestion(
                suggestion_id=f"anomaly_{datetime.now().timestamp()}",
                suggestion_type="anomaly",
                title="⏰ Missed Morning Routine",
                description=f"You typically {anomaly['pattern'].trigger_condition.get('activity_type')} around {anomaly['pattern'].trigger_condition.get('typical_hour', 8):.1f}:00. Want me to activate sick day mode?",
                priority=2,
                action_items=["Activate sick day mode", "Reschedule meetings", "Send status update"],
                auto_execute=False,
                requires_approval=True,
                context=anomaly,
                confidence=anomaly["pattern"].confidence
            )
        
        elif anomaly_type == AnomalyType.UNUSUAL_INACTIVITY:
            return ProactiveSuggestion(
                suggestion_id=f"anomaly_{datetime.now().timestamp()}",
                suggestion_type="anomaly",
                title="🔔 Unusual Inactivity Detected",
                description=f"No activity detected for {anomaly['inactive_hours']:.1f} hours. Everything okay?",
                priority=3,
                action_items=["Check in", "Review pending tasks"],
                auto_execute=False,
                requires_approval=True,
                context=anomaly,
                confidence=0.8
            )
        
        elif anomaly_type == AnomalyType.INBOX_BACKLOG:
            return ProactiveSuggestion(
                suggestion_id=f"anomaly_{datetime.now().timestamp()}",
                suggestion_type="anomaly",
                title="📧 Inbox Growing",
                description=f"You have {anomaly.get('unread_count', 'many')} unread emails. Want me to summarize the urgent ones?",
                priority=2,
                action_items=["Summarize urgent emails", "Filter by priority", "Draft responses"],
                auto_execute=False,
                requires_approval=True,
                context=anomaly,
                confidence=0.9
            )
        
        elif anomaly_type == AnomalyType.CALENDAR_CONFLICT:
            return ProactiveSuggestion(
                suggestion_id=f"anomaly_{datetime.now().timestamp()}",
                suggestion_type="anomaly",
                title="📅 Calendar Conflict Detected",
                description=f"Overlapping events detected: {anomaly.get('conflict_description', '')}",
                priority=1,
                action_items=["Show resolution options", "Propose new time", "Notify attendees"],
                auto_execute=False,
                requires_approval=True,
                context=anomaly,
                confidence=0.95
            )
        
        return ProactiveSuggestion(
            suggestion_id=f"anomaly_{datetime.now().timestamp()}",
            suggestion_type="anomaly",
            title="⚠️ Anomaly Detected",
            description=str(anomaly.get("description", "Unknown anomaly")),
            priority=3,
            action_items=["Review details"],
            auto_execute=False,
            requires_approval=True,
            context=anomaly,
            confidence=0.5
        )
    
    def _create_opportunity_suggestion(self, opportunity: Dict) -> ProactiveSuggestion:
        """Create a suggestion from an opportunity."""
        opp_type = opportunity.get("type")
        
        if opp_type == OpportunityType.LEARNING_MOMENT:
            return ProactiveSuggestion(
                suggestion_id=f"opp_{datetime.now().timestamp()}",
                suggestion_type="opportunity",
                title="💡 Automation Opportunity",
                description=opportunity["description"],
                priority=4,
                action_items=["Learn the task pattern", "Create automation script", "Test solution"],
                auto_execute=False,
                requires_approval=True,
                context=opportunity,
                confidence=0.7
            )
        
        elif opp_type == OpportunityType.MARKET_MOVEMENT:
            pattern = opportunity.get("pattern")
            return ProactiveSuggestion(
                suggestion_id=f"opp_{datetime.now().timestamp()}",
                suggestion_type="opportunity",
                title="📊 Ready for Your Morning Check",
                description=f"It's almost {pattern.trigger_condition.get('typical_hour', 8):.1f}:00. Here's your overnight summary ready.",
                priority=3,
                action_items=["Show crypto summary", "Show news brief", "Show calendar"],
                auto_execute=True,
                requires_approval=False,
                context=opportunity,
                confidence=pattern.confidence
            )
        
        return ProactiveSuggestion(
            suggestion_id=f"opp_{datetime.now().timestamp()}",
            suggestion_type="opportunity",
            title="🎯 Opportunity Detected",
            description=opportunity.get("description", "Unknown opportunity"),
            priority=4,
            action_items=["Explore opportunity"],
            auto_execute=False,
            requires_approval=True,
            context=opportunity,
            confidence=opportunity.get("value_score", 5) / 10
        )
    
    # ==================== CALLBACKS ====================
    
    def register_pattern_callback(self, pattern_type: str, callback: Callable):
        """Register a callback for when a pattern is detected."""
        if pattern_type not in self.pattern_callbacks:
            self.pattern_callbacks[pattern_type] = []
        self.pattern_callbacks[pattern_type].append(callback)
    
    def _trigger_callbacks(self, pattern_type: str, data: Dict):
        """Trigger registered callbacks for a pattern type."""
        for callback in self.pattern_callbacks.get(pattern_type, []):
            try:
                callback(data)
            except Exception as e:
                self.logger.error(f"Callback error: {e}")
    
    # ==================== UTILITIES ====================
    
    def get_patterns_summary(self) -> Dict:
        """Get summary of learned patterns."""
        return {
            "total_patterns": len(self.user_patterns),
            "high_confidence": len([p for p in self.user_patterns if p.confidence > 0.8]),
            "by_type": {
                "time": len([p for p in self.user_patterns if p.pattern_type == "time"]),
                "action": len([p for p in self.user_patterns if p.pattern_type == "action"]),
                "sequence": len([p for p in self.user_patterns if p.pattern_type == "sequence"]),
                "threshold": len([p for p in self.user_patterns if p.pattern_type == "threshold"])
            },
            "last_activity": self.last_activity.isoformat()
        }
    
    def export_patterns(self, filepath: str):
        """Export patterns to file."""
        data = {
            "patterns": [asdict(p) for p in self.user_patterns],
            "exported_at": datetime.now().isoformat()
        }
        Path(filepath).write_text(json.dumps(data, indent=2, default=str))
    
    def clear_patterns(self):
        """Clear all learned patterns."""
        self.user_patterns = []
        self._save_patterns()
        self.logger.info("All patterns cleared")